name: Build and Release Keyhunt

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'build?'
        type: boolean
        required: false
        default: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libgmp-dev

    - name: Clone Keyhunt repository
      run: git clone https://github.com/albertobsd/keyhunt.git

    - name: Compile Keyhunt and Meuhunt
      run: |
        cd keyhunt
        make # This will build both keyhunt and meuhunt as per its Makefile

    - name: Upload 'keyhunt' Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./keyhunt/keyhunt
        asset_name: keyhunt
        asset_content_type: application/octet-stream

    - name: Upload 'meuhunt' Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Ensure this is also correctly sourced
      with:
        upload_url: ${{ github.event.release.upload_url }} # This was missing
        asset_path: ./keyhunt/meuhunt
        asset_name: meuhunt
        asset_content_type: application/octet-stream
