name: Build and Release Keyhunt

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'build?'
        type: boolean
        required: false
        default: true
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libgmp-dev

    - name: Clone Keyhunt repository
      run: git clone https://github.com/albertobsd/keyhunt.git

    - name: Compile Keyhunt and Rename to Meuhunt
      run: |
        cd keyhunt
        make
        mv keyhunt meuhunt

    - name: Upload 'meuhunt' Artifact
      uses: actions/upload-artifact@v4
      with:
        name: meuhunt
        path: ./keyhunt/*
